# Generated by Django 4.1.1 on 2022-09-20 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(5, 'Минимум 5 символов')], verbose_name='Район поиска'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Минимум 5 символов')], verbose_name='Тэги'),
        ),
    ]
