# Generated by Django 4.0.6 on 2022-08-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_admin', '0002_auto_20220723_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgusers',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=17, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='tgusers',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=17, null=True, verbose_name='Долгота'),
        ),
    ]
